{% set name = "opentelemetry-propagator-aws-xray" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/opentelemetry-propagator-aws-xray-{{ version }}.tar.gz
  sha256: 2e2cf932b8b4f3912b817d18973f16c3498b25bcfb6f03cac71b3f3b7175c191

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - opentelemetry-api >=1.3,<2.dev0

test:
  imports:
    - opentelemetry.propagators.aws
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/open-telemetry/opentelemetry-python-contrib/tree/main/propagator/opentelemetry-propagator-aws-xray
  summary: AWS X-Ray Propagator for OpenTelemetry
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
